# Generated by Django 5.2.12 on 2026-03-29 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitysignal',
            name='source',
            field=models.CharField(blank=True, default='dehashed', max_length=50),
        ),
        migrations.CreateModel(
            name='OsintResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('leakcheck', 'Leakcheck'), ('securitytrails', 'Securitytrails'), ('shodan', 'Shodan'), ('censys', 'Censys'), ('builtwith', 'Builtwith'), ('hibp', 'Hibp')], max_length=50)),
                ('raw_response', models.JSONField(default=dict)),
                ('result_count', models.IntegerField(default=0)),
                ('query_value', models.CharField(max_length=255)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osint_results', to='intelligence.analysis')),
            ],
            options={
                'db_table': 'osint_results',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('analysis', 'source')},
            },
        ),
    ]
