# Generated by Django 5.2.12 on 2026-03-29 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(max_length=500)),
                ('executive_narrative', models.TextField()),
                ('talk_track', models.TextField()),
                ('business_impact', models.TextField()),
                ('transition', models.TextField()),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_hash', models.CharField(blank=True, default='', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative', to='intelligence.analysis')),
            ],
            options={
                'db_table': 'narratives',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
