# Generated by Django 5.2.12 on 2026-03-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='category_findings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='narrative',
            name='risk_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
