# Generated by Django 5.2.12 on 2026-03-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0002_narrative_category_findings_narrative_risk_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrative',
            name='business_impact',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='category_findings',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='executive_narrative',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='risk_summary',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='talk_track',
        ),
        migrations.AddField(
            model_name='narrative',
            name='correlated_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='narrative',
            name='executive_brief',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='narrative',
            name='findings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='transition',
            field=models.TextField(blank=True, default=''),
        ),
    ]
